### ISSUE TITLE
Fails to launch on Deno Deploy

### ISSUE THREAD

**Issue by awestbro** [sachinraja/trpc-ultra#2]
I've been trying to get this running on Deno Deploy and have upgraded to the latest beta version of @trpc/client but when running on Deno Deploy, I get a server error: 

TRPCClientError: Unexpected non-whitespace character after JSON at position 3
    at Function.from (file:///src/vendor/server/esm.sh/v96/@trpc/client@10.0.0-proxy-beta.24/X-ZS8q/deno/links/httpBatchLink.js:2:155)
    at file:///src/vendor/server/esm.sh/v96/@trpc/client@10.0.0-proxy-beta.24/X-ZS8q/deno/links/httpBatchLink.js:2:4047

Do you have any clue where I could further investigate this error?

**Comment by sachinraja** [comment]
This is because Deno Deploy does not allow requests to the deployment inside of the deployment: https://github.com/denoland/deploy_feedback/issues/187. This is necessary for SSR though. Not sure how to fix it.
